//---------------------------------------------------------------------------

#include <vcl.h>
#pragma hdrstop
USEFORM("Main.cpp", Tee9Form);
USEFORM("Welcome.cpp", WelcomeForm);
USEFORM("Base.cpp", BaseForm);
USEFORM("Canvas_OrthoAngle.cpp", OrthoAngle);
USEFORM("Area_Origin.cpp", AreaOriginForm);
USEFORM("Gradient_MidColor.cpp", GradientMiddle);
USEFORM("Base_CustomPos.cpp", BaseCustomPos);
USEFORM("Base_DBChart.cpp", BaseDBChart);
USEFORM("Area_Stairs.cpp", AreaStairsForm);
USEFORM("Canvas_RotCenter.cpp", RotationCenter);
USEFORM("Canvas_DotPen.cpp", CanvasDotPen);
USEFORM("Brush_Styles.cpp", BrushStyleForm);
USEFORM("Canvas_Cone.cpp", ConesForm);
USEFORM("Assign_Picture.cpp", AssignPicture);
USEFORM("Canvas_PyramidTrunc.cpp", TruncPyramidForm);
USEFORM("Canvas_Transparency.cpp", TransparencyForm);
USEFORM("Right_Wall.cpp", RightWallForm);
USEFORM("BackWall_Gradient.cpp", BackWallGradient);
USEFORM("BackWall_Image.cpp", BackWallImage);
USEFORM("Chart_SubTitles.cpp", SubTitles);
USEFORM("Title_CustomPos.cpp", TitleCustomPos);
USEFORM("Title_ClickEvent.cpp", TitleClickEvent);
USEFORM("Title_GenFormat.cpp", TitleGenFormat);
USEFORM("Axis_Behind.cpp", AxisBehind);
USEFORM("Axis_Custom.cpp", AxisCustom);
USEFORM("AxisTitle_Visible.cpp", AxisTitleVisible);
USEFORM("Axis_Millisec.cpp", AxisMillisec);
USEFORM("Axis_Exponent.cpp", AxisLabelExp);
USEFORM("Axis_LabelAlign.cpp", AxisLabelAlignForm);
USEFORM("Axis_MinorGrid.cpp", AxisMinorGrid);
USEFORM("Legend_CustomPos.cpp", LegendCustomPos);
USEFORM("Legend_Widths.cpp", LegendWidths);
USEFORM("Legend_CheckBox.cpp", LegendCheckbox);
USEFORM("Legend_Image.cpp", LegendImage);
USEFORM("Legend_VertSpa.cpp", LegendVertSpa);
USEFORM("Legend_Symbol.cpp", LegendSymbolForm);
USEFORM("Axis_OpaqueZone.cpp", AxisOpaqueZone);
USEFORM("Axis_MultiScroll.cpp", MultiAxisScroll);
USEFORM("Axis_MultiRuntime.cpp", AxisMultiRuntime);
USEFORM("Canvas_GrayScale.cpp", GrayScaleForm);
USEFORM("Chart_OnBeforeDraw.cpp", ChartBeforeDraw);
USEFORM("Legend_TextStyle.cpp", LegendStyleForm);
USEFORM("Legend_CurrentPage.cpp", LegendCurrentPage);
USEFORM("Legend_FontColor.cpp", LegendFontColor);
USEFORM("Legend_GenFormat.cpp", LegendGenFormat);
USEFORM("Legend_Series.cpp", LegendSeriesForm);
USEFORM("Legend_Multi.cpp", MultiLegendForm);
USEFORM("Legend_AddText.cpp", LegendAddText);
USEFORM("Print_Pages.cpp", PrintPagesForm);
USEFORM("Print_Preview.cpp", PrintPreviewForm);
USEFORM("PrintPreview_Navigate.cpp", PrintPreviewNavigate);
USEFORM("PrintPreview_Multi.cpp", PrintPreviewMulti);
USEFORM("Zoom_Pen.cpp", ZoomPen);
USEFORM("Zoom_MinPix.cpp", ZoomMinPixel);
USEFORM("Zoom_Direction.cpp", ZoomDirection);
USEFORM("DBChart_Speed.cpp", DBChartSpeed);
USEFORM("DBChart_Summary.cpp", DBChartSummary);
USEFORM("DBChart_Order.cpp", DBChartOrder);
USEFORM("DBChart_LocateRecord.cpp", DBChartRecordLocate);
USEFORM("Function_MovAveWeighted.cpp", MovAveWeightedForm);
USEFORM("RSI_Function.cpp", RSICalcForm);
USEFORM("Function_AverageNulls.cpp", AverageFunctionNulls);
USEFORM("Marks_Shadow.cpp", MarksShadow);
USEFORM("Marks_Angle.cpp", MarksAngle);
USEFORM("Marks_DrawEvery.cpp", MarksEvery);
USEFORM("Marks_XYStyle.cpp", MarksXYStyle);
USEFORM("Marks_Multi.cpp", MarksMulti);
USEFORM("Marks_Positions.cpp", MarksPositions);
USEFORM("Marks_GenFormat.cpp", MarksGenFormat);
USEFORM("SeriesType_Area.cpp", AreaSeriesForm);
USEFORM("SeriesType_Bezier.cpp", BezierSeriesForm);
USEFORM("Bar_SideAll.cpp", BarSideAll);
USEFORM("Bar_StackGroup.cpp", BarStackGroup);
USEFORM("Series_BarNegativeStacked.cpp", BarStackNegative);
USEFORM("Bar_Image.cpp", BarImage);
USEFORM("Bar_Gradient.cpp", BarGradient);
USEFORM("Candle_CustomColors.cpp", CandleCustomColors);
USEFORM("Candle_OpenClose.cpp", CandleOpenClose);
USEFORM("Candle_AxisLabels.cpp", CandleAxisLabels);
USEFORM("SeriesType_Contour.cpp", ContourSeriesForm);
USEFORM("Contour_Levels.cpp", ContourLevelsForm);
USEFORM("Contour_View2D.cpp", ContourView2D);
USEFORM("Contour_Palette.cpp", ContourPaletteForm);
USEFORM("ErrorBar_Negative.cpp", ErrorBarNegativeForm);
USEFORM("Line_Stack.cpp", LineStack);
USEFORM("Line_Clickable.cpp", LineClickableForm);
USEFORM("Line_Pattern.cpp", LinePatternForm);
USEFORM("Line_ColorEachLine.cpp", LineColorEachLine);
USEFORM("Pie_Multi.cpp", PieMultiple);
USEFORM("Pie_Semi.cpp", PieSemi);
USEFORM("Pointer_DrawCanvas.cpp", PointerDrawCanvas);
USEFORM("SeriesType_Point3D.cpp", Point3DSeriesForm);
USEFORM("Point3D_Event.cpp", Point3DEvent);
USEFORM("Polar_ClockWise.cpp", PolarClockWise);
USEFORM("Polar_LabelsInside.cpp", PolarLabelsInside);
USEFORM("Shape_Image.cpp", ShapeImage);
USEFORM("Shape_VertAlign.cpp", ShapeVertAlign);
USEFORM("SeriesType_Surface.cpp", SurfaceSeriesForm);
USEFORM("Surface_Sides.cpp", SurfaceSidesDemo);
USEFORM("Surface_Smooth.cpp", SurfaceSmooth);
USEFORM("Surface_Irregular.cpp", SurfaceFloat);
USEFORM("Surface_XYZFloat.cpp", SurfaceFloatOther);
USEFORM("Surface_WirePalette.cpp", SurfaceWire);
USEFORM("Surface_Palette.cpp", SurfacePaletteForm);
USEFORM("WindRose_AngleInc.cpp", WindAngleInc);
USEFORM("Series3D_RangePalette.cpp", Series3DRangePalette);
USEFORM("Chart_FreeAllSeries.cpp", FreeAllSeriesForm);
USEFORM("Series_Depth.cpp", SeriesDepth);
USEFORM("Clock_Editors.cpp", ClockEdi);
USEFORM("Chart_Gallery.cpp", ChartGallery);
USEFORM("Chart_SubGallery.cpp", ChartSubGallery);
USEFORM("Order_Info.cpp", OrderInfo);
USEFORM("Removed_Properties.cpp", RemovedProperties);
USEFORM("Changes_Package.cpp", ChangesPackage);
USEFORM("Changes_Misc.cpp", ChangesMisc);
USEFORM("TeeCustomShape.cpp", CustomShape);
USEFORM("Tool_Cursor.cpp", CursorToolDemo);
USEFORM("Tool_DragMarks.cpp", DragMarksToolDemo);
USEFORM("Series_ValueList.cpp", DynArrays);
USEFORM("Tool_AxisArrow.cpp", AxisArrowToolDemo);
USEFORM("Tools_DrawLine.cpp", DrawLineToolDemo);
USEFORM("Tools_Nearest.cpp", NearestToolDemo);
USEFORM("Tool_MarksTip.cpp", MarkTipsToolDemo);
USEFORM("Tools_ColorBand.cpp", ColorBandToolForm);
USEFORM("ColorBand_Transparent.cpp", ColorBandTransp);
USEFORM("Tools_ColorLine.cpp", ColorLineForm);
USEFORM("Tool_Rotate.cpp", RotateToolForm);
USEFORM("Tools_Image.cpp", ImageToolForm);
USEFORM("Tools_Custom.cpp", AxisLabelToolDemo);
USEFORM("Tool_PageNumDemo.cpp", PageNumToolDemo);
USEFORM("Tool_DragPoint.cpp", DragPointToolDemo);
USEFORM("Chart_Grid.cpp", ChartGridForm);
USEFORM("Chart_EditorPanel.cpp", ChartEditorPanelForm);
USEFORM("Gallery_Panel.cpp", GalleryPanelForm);
USEFORM("Chart_PageNavigator.cpp", PageNavigatorForm);
USEFORM("Chart_WebSource.cpp", ChartWebSourceForm);
USEFORM("Series_TextSource.cpp", SeriesTextSourceForm);
USEFORM("ValueList_FindMinMax.cpp", FindMinMaxValues);
USEFORM("ValueList_Modified.cpp", ValueListModified);
USEFORM("Printing_Bugs.cpp", PrintingBugsForm);
USEFORM("ColorRange_Bug.cpp", ColorRangeBug);
USEFORM("Bar_Cylinder.cpp", BarCylinderForm);
USEFORM("Exponential_Trend.cpp", ExponentialTrendForm);
USEFORM("MomentumDiv_Function.cpp", MomentumDivForm);
USEFORM("MACD_Function.cpp", MACDForm);
USEFORM("Welcome_All.cpp", WelcomeAllForm);
USEFORM("Stochastic_Function.cpp", StochasticForm);
USEFORM("Function_ExpMovAve.cpp", ExpMovAveForm);
USEFORM("Function_RootMeanSq.cpp", RootMeanSqForm);
USEFORM("Function_Bollinger.cpp", BollingerForm);
USEFORM("Function_ADX.cpp", ADXFunctionForm);
USEFORM("Donut_Series.cpp", DonutSeriesForm);
USEFORM("TriSurface_Series.cpp", TriSurfaceForm);
USEFORM("BoxPlot_Series.cpp", BoxPlotForm);
USEFORM("Histogram_Series.cpp", HistogramForm);
USEFORM("ColorGrid_Series.cpp", ColorGrid);
USEFORM("ColorGrid_Transparent.cpp", ColorGridTransparent);
USEFORM("Mouse_Wheel.cpp", MouseWheelForm);
USEFORM("HorizLine_Series.cpp", HorizLineForm);
USEFORM("BarJoin_Series.cpp", BarJoinForm);
USEFORM("HighLow_Series.cpp", HighLowForm);
USEFORM("WaterFall_Series.cpp", WaterFallForm);
USEFORM("Smith_Series.cpp", SmithForm);
USEFORM("Pyramid_Series.cpp", PyramidForm);
USEFORM("Map_Series.cpp", MapSeriesForm);
USEFORM("Series_Calendar.cpp", CalendarSeriesForm);
USEFORM("Series_Funnel.cpp", FunnelSeriesForm);
USEFORM("Chart_Transparent.cpp", ChartTransparent);
USEFORM("Editor_Color.cpp", EditorColor);
USEFORM("Series_Designer.cpp", SeriesDesigner);
USEFORM("Chart_Actions.cpp", ChartActionsForm);
USEFORM("Export_Charts.cpp", ExportChartsForm);
USEFORM("Export_Text.cpp", ExportTextForm);
USEFORM("Export_HTML.cpp", ExportHTMLForm);
USEFORM("Export_XML.cpp", ExportXMLForm);
USEFORM("Export_Excel.cpp", ExportExcelForm);
USEFORM("Export_GIF.cpp", GIFExportForm);
USEFORM("Export_JPEG.cpp", JPEGExportForm);
USEFORM("Export_PNG.cpp", PNGExportForm);
USEFORM("Export_PCX.cpp", PCXExportForm);
USEFORM("Export_Email.cpp", ExportEmailForm);
USEFORM("Template_Chart.cpp", TemplateChart);
USEFORM("ChartEditor_Dialog.cpp", ChartEditorForm);
USEFORM("Chart_Commander.cpp", TeeCommanderForm);
USEFORM("Chart_ListBox.cpp", ChartListBoxForm);
USEFORM("OpenGL_Editor.cpp", OpenGLEditorForm);
USEFORM("OpenGL_Surface.cpp", OpenGLSurface);
USEFORM("OpenGL_TriSurface.cpp", OpenGLTriSurface);
USEFORM("OpenGL_Canvas.cpp", OpenGLCanvas);
USEFORM("OpenGL_Football.cpp", OpenGLFootBall);
USEFORM("Basic_Features.cpp", BasicFeatures);
USEFORM("SeriesType_Line.cpp", LineSeriesForm);
USEFORM("SeriesType_Bar.cpp", BarSeriesForm);
USEFORM("SeriesType_Pie.cpp", PieSeriesForm);
USEFORM("SeriesType_FastLine.cpp", FastLineForm);
USEFORM("SeriesType_HorizBar.cpp", HorizBarSeriesForm);
USEFORM("SeriesType_Point.cpp", PointSeriesForm);
USEFORM("SeriesType_Bubble.cpp", BubbleSeriesForm);
USEFORM("SeriesType_Arrow.cpp", ArrowSeriesForm);
USEFORM("SeriesType_Gantt.cpp", GanttSeriesForm);
USEFORM("Series_Shape.cpp", ShapeSeriesForm);
USEFORM("SeriesType_Candle.cpp", CandleForm);
USEFORM("SeriesType_Volume.cpp", VolumeForm);
USEFORM("Surface_Hole.cpp", SurfaceHolesForm);
USEFORM("SeriesType_Polar.cpp", PolarForm);
USEFORM("SeriesType_Radar.cpp", RadarForm);
USEFORM("Series_Error.cpp", ErrorSeriesForm);
USEFORM("WindRose_Series.cpp", WindRoseForm);
USEFORM("Reporting_Tools.cpp", ChartReports);
USEFORM("Customers.cpp", TeeCustomers);
USEFORM("Chart_Other.cpp", ChartOther);
USEFORM("SeriesType_Clock.cpp", ClockSeriesForm);
USEFORM("Series_Bar3D.cpp", Bar3DForm);
USEFORM("Series_MyPoint.cpp", MyPointSeriesForm);
USEFORM("Series_ImageBar.cpp", ImageBarForm);
USEFORM("Series_ImagePoint.cpp", ImagePointForm);
USEFORM("Series_DeltaPoint.cpp", DeltaPointForm);
USEFORM("Series_BigCandle.cpp", BigCandleForm);
USEFORM("DBChart_AnyDataSet.cpp", DBChartAny);
USEFORM("DBChart_SingleRecord.cpp", DBChartSingleRecord);
USEFORM("DBChart_MasterDetail.cpp", LinkedTablesForm);
USEFORM("DBChart_CrossTab.cpp", DBChartCrossTab);
USEFORM("Print_PreviewDialog.cpp", PrintPreviewDialog);
USEFORM("FourCharts.cpp", FourChartsForm);
USEFORM("Export_Metafile.cpp", MetafileForm);
USEFORM("Function_Subtract.cpp", SubtractForm);
USEFORM("Function_High.cpp", HighForm);
USEFORM("Function_Low.cpp", LowForm);
USEFORM("Function_Count.cpp", CountForm);
USEFORM("Function_Add.cpp", FunctionAddForm);
USEFORM("Function_Multiply.cpp", MultiplyForm);
USEFORM("Function_Divide.cpp", DivideForm);
USEFORM("Function_Average.cpp", AverageForm);
USEFORM("Function_ExpAve.cpp", ExpAveForm);
USEFORM("Function_StdDeviation.cpp", StdDeviationForm);
USEFORM("Function_CurveFitting.cpp", CurveFittingForm);
USEFORM("CurveFitting_Coef.cpp", CurveFittingCoef);
USEFORM("CurveFitting_Dynamic.cpp", DynamicTrend);
USEFORM("Function_Trend.cpp", TrendForm);
USEFORM("Function_Cumulative.cpp", CumulativeForm);
USEFORM("Function_MovAve.cpp", MovAveFunctionForm);
USEFORM("Function_RSI.cpp", RSIFunctionForm);
USEFORM("Function_Momentum.cpp", MomentumForm);
USEFORM("QualityControl.cpp", FormQuality);
USEFORM("ChartEditor_Runtime.cpp", ChartEditorRuntime);
USEFORM("ChartListBox_Demo.cpp", ListBoxForm);
USEFORM("Draw3D_Canvas.cpp", Draw3DCanvas);
USEFORM("Chart_PrintPreview.cpp", ChartPrintPreviewForm);
USEFORM("Chart_ScrollBar.cpp", ChartScrollBarForm);
USEFORM("Series_DataSet.cpp", SeriesDataSetForm);
USEFORM("TeeCommander_Demo.cpp", TeeCommanderDemo);
USEFORM("Internet_Charts.cpp", InternetCharts);
USEFORM("Chart_Axes.cpp", ChartAxesForm);
USEFORM("Zoom_Scroll.cpp", ZoomScrollForm);
USEFORM("Legend_Scroll.cpp", LegendScroll);
USEFORM("Drag_Bars.cpp", DragBarForm);
USEFORM("Chart_Clipboard.cpp", ChartClipboard);
USEFORM("Chart_MultiClipboard.cpp", ChartMultiClipboard);
USEFORM("Area_Transparency.cpp", AreaTransparency);
USEFORM("Line_Outline.cpp", LineOutline);
USEFORM("PolarRadar_Transparency.cpp", PolarRadarTransp);
USEFORM("Tool_Annotation.cpp", AnnotationToolForm);
USEFORM("Tool_CursorProg.cpp", CursorToolProg);
USEFORM("Tool_CursorSynchro.cpp", CursorSynchro);
USEFORM("Tool_DrawLineDragged.cpp", DrawLineOnDragged);
USEFORM("ColorLine_DragRepaint.cpp", ColorLineDragRepaint);
USEFORM("ChartGrid_Colors.cpp", ChartGridColors);
USEFORM("TriSurface_Hidding.cpp", TriSurfaceHidding);
USEFORM("Histogram_Transparency.cpp", HistogramTransp);
USEFORM("ColorGrid_Clicked.cpp", ColorGridClicked);
USEFORM("Calendar_Buttons.cpp", CalendarButtons);
USEFORM("Export_VML.cpp", ExportVMLForm);
USEFORM("Commander_Custom.cpp", CommanderCustom);
USEFORM("Chart_MultiLanguage.cpp", ChartMultiLanguage);
USEFORM("Candle_OnGetPointer.cpp", CandleOnGetPointer);
USEFORM("Volume_Origin.cpp", VolumeOrigin);
USEFORM("FastLine_DrawAll.cpp", FastLineDrawAll);
USEFORM("ChartEditor_PageNum.cpp", ChartEditorPageNum);
USEFORM("MarkTips_MouseDelay.cpp", MarksTipMouseDelay);
USEFORM("Release502_NewFeatures.cpp", Release502Misc);
USEFORM("Release502_FixedBugs.cpp", Release502Fixed);
USEFORM("TeeChartWizardDemo.cpp", ChartWizardDemo);
USEFORM("Release501_NewFeatures.cpp", Release501Misc);
USEFORM("Release501_FixedBugs.cpp", Release501Fixed);
USEFORM("Pie_Shadow.cpp", PieShadowForm);
USEFORM("Area_Gradient.cpp", AreaGradient);
USEFORM("Font_Gradient.cpp", FontGradient);
USEFORM("ComboFlat_Demo.cpp", ComboFlatForm);
USEFORM("Inspector_Demo.cpp", InspectorForm);
USEFORM("ChartImage_Demo.cpp", ChartImageForm);
USEFORM("DrawLine_Style.cpp", DrawLineStyleForm);
USEFORM("Release503_NewFeatures.cpp", Release503Misc);
USEFORM("Release503_FixedBugs.cpp", Release503Fixed);
USEFORM("FastLine_Realtime.cpp", FastDeleteRealtime);
USEFORM("Tool_AnnotationClick.cpp", AnnotationClickForm);
USEFORM("Series_BarSize.cpp", BarSizeSeriesForm);
USEFORM("PostScript_Demo.cpp", PostScriptForm);
USEFORM("Gantt_MouseDrag.cpp", GanttMouseForm);
USEFORM("Axes_ZPosition.cpp", AxesZPosition);
USEFORM("Axes_Offsets.cpp", AxesOffsets);
USEFORM("Axis_Items.cpp", AxisItemsDemo);
USEFORM("Axes_LabelsFormat.cpp", AxesLabelsFormat);
USEFORM("Axis_LabelsFormat.cpp", AxisLabelsFormat);
USEFORM("Canvas_180Rotation.cpp", Canvas180Rotation);
USEFORM("Gradient_RadialCenter.cpp", GradientRadial);
USEFORM("Canvas_AntiAlias.cpp", CanvasAntiAlias);
USEFORM("Canvas_RotatedEllipse.cpp", CanvasRotatedEllipse);
USEFORM("RichText_Drawing.cpp", RichTextDrawing);
USEFORM("Legend_SymbolBorder.cpp", LegendSymbolBorder);
USEFORM("Wall_Transparency.cpp", WallTransparency);
USEFORM("Margins_Units.cpp", ChartMarginUnits);
USEFORM("Chart_Shadow.cpp", ChartShadow);
USEFORM("Chart_RoundPanel.cpp", ChartRoundPanel);
USEFORM("DBChart_SummaryOrder.cpp", DBSummaryOrder);
USEFORM("ColorLine_Draw3D.cpp", ColorLine3D);
USEFORM("Tool_AnnotationCallout.cpp", AnnotationCO);
USEFORM("Tool_RotateOutline.cpp", RotateOutline);
USEFORM("Series_MouseEnter.cpp", SeriesMouseEnter);
USEFORM("Series_SortLabels.cpp", SeriesSortLabel);
USEFORM("Marks_Callout.cpp", MarksCallouts);
USEFORM("Marks_PerPoint.cpp", MarksPerPoint);
USEFORM("Bar_SelfStack.cpp", BarSelfStack);
USEFORM("BoxSeries_CustomValues.cpp", BoxCustomForm);
USEFORM("Bubble_Gradient.cpp", BubbleGradient);
USEFORM("Bubble_Transparency.cpp", BubbleTransparency);
USEFORM("ColorGrid_Marks.cpp", ColorGridMarks);
USEFORM("ColorGrid_Bitmap.cpp", ColorGridBitmap);
USEFORM("Contour_SmoothSegments.cpp", ContourSmooth);
USEFORM("Contour_OnBeforeDraw.cpp", ContourOnBefore);
USEFORM("FastLine_Nulls.cpp", FastLineNulls);
USEFORM("Pie_AutoMarkPosition.cpp", PieAutoMarkPos);
USEFORM("Pie_OtherLegend.cpp", PieOtherLegend);
USEFORM("Circled_Gradient.cpp", CircledGradient);
USEFORM("Polar_Zones.cpp", PolarZones);
USEFORM("Surface_Transparency.cpp", SurfaceTransp);
USEFORM("Series3D_AddArray.cpp", AddArray3D);
USEFORM("XYZ_Gridding.cpp", XYZGridding);
USEFORM("Preview_CustomDraw.cpp", PreviewCustomDraw);
USEFORM("ChartGrid_Grid3D.cpp", ChartGrid3D);
USEFORM("Tool_3DTranspose.cpp", TransposeToolDemo);
USEFORM("Tool_ExtraLegend.cpp", ExtraLegendDemo);
USEFORM("Tools_SeriesAnim.cpp", SeriesAnimDemo);
USEFORM("Axes_GridBands.cpp", AxesGridBands);
USEFORM("Tool_Pie.cpp", PieToolDemo);
USEFORM("Series_XMLSource.cpp", XMLSourceDemo);
USEFORM("Series_XMLSourceWeb.cpp", XMLSourceWeb);
USEFORM("DBChart_CrossTabSource.cpp", DBCrossTabSourceDemo);
USEFORM("Function_Smoothing.cpp", SmoothingFunctionDemo);
USEFORM("Function_Custom.cpp", CustomFunctionDemo);
USEFORM("Function_Compression.cpp", CompressionDemo);
USEFORM("Function_CrossPoints.cpp", CrossPointsDemo);
USEFORM("Function_CLV.cpp", CLVFuncDemo);
USEFORM("Function_OBV.cpp", OBVFuncDemo);
USEFORM("Function_CCI.cpp", CCIFuncDemo);
USEFORM("Function_PVO.cpp", PVOFuncdemo);
USEFORM("Function_Performance.cpp", PerfFuncDemo);
USEFORM("SeriesType_HorizArea.cpp", HorizAreaSeriesForm);
USEFORM("Series_PointFigure.cpp", PointFigureDemo);
USEFORM("Series_Gauge.cpp", GaugeDemo);
USEFORM("Series_Vector3D.cpp", Vector3DSeriesForm);
USEFORM("SeriesType_Tower.cpp", TowerSeriesForm);
USEFORM("Export_PDF.cpp", PDFExportForm);
USEFORM("Property_Aliases.cpp", PropertyAliases);
USEFORM("GridToChart_Demo.cpp", GridToChartDemo);
USEFORM("Release6_Misc.cpp", MiscVersion6);
USEFORM("Release6_FixedBugs.cpp", Release6Fixed);
USEFORM("Chart_Themes.cpp", ChartThemes);
USEFORM("Chart_Palettes.cpp", CustomPalettes);
USEFORM("Axis_LabelsAlternate.cpp", AlternateAxisLabels);
USEFORM("Axis_DepthTop.cpp", DepthTopAxisForm);
USEFORM("Legend_Title.cpp", LegendTitleForm);
USEFORM("Bar_TickLines.cpp", BarTickLines);
USEFORM("Marks_Symbols.cpp", MarkSymbols);
USEFORM("Pie_ShadowEllipse.cpp", PieShadowEllipse);
USEFORM("Tool_Lighting.cpp", LightToolForm);
USEFORM("Tool_SurfaceNearest.cpp", SurfaceNearestForm);
USEFORM("ChartListBox_Radio.cpp", ChartListBoxRadio);
USEFORM("ChartListBox_Editor.cpp", ChartListBoxEditor);
USEFORM("Commander_CustomEditor.cpp", CommanderCustomEditor);
USEFORM("Gallery_Smooth.cpp", GallerySmooth);
USEFORM("Function_Mode.cpp", ModeFunctionDemo);
USEFORM("Function_Median.cpp", MedianFunctionDemo);
USEFORM("Function_Correlation.cpp", CorrelationFunctionDemo);
USEFORM("Function_Variance.cpp", VarianceDemo);
USEFORM("Function_Perimeter.cpp", PerimeterDemo);
USEFORM("Series_Bubble3D.cpp", Bubble3DSeriesForm);
USEFORM("Series_HorizHisto.cpp", HorizHistoForm);
USEFORM("Export_SVG.cpp", SVGExportForm);
USEFORM("Pie_Gradient.cpp", PieGradientForm);
USEFORM("Point3D_BaseLine.cpp", Point3DBaseLine);
USEFORM("ColorBand_Clicked.cpp", ColorBandClicked);
USEFORM("Canvas_SmoothStretch.cpp", CanvasSmoothStretch);
USEFORM("Release7_Misc.cpp", MiscVersion7);
USEFORM("Release7_FixedBugs.cpp", Release7Fixed);
USEFORM("Gallery_Alternate.cpp", GalleryAlternate);
USEFORM("Axis_Isometric.cpp", IsometricAxis);
USEFORM("Axes_DrawBevels.cpp", BeveledAxes);
USEFORM("Axis_FirstLastLabels.cpp", FirstLastLabels);
USEFORM("Axis_DepthDateTime.cpp", DepthAxisDateTime);
USEFORM("Legend_Scrollbar.cpp", LegendScrollBarDemo);
USEFORM("Legend_SymbolFlags.cpp", LegendSymbolDraw);
USEFORM("Bar_3DDepth.cpp", Bar3DDepth);
USEFORM("Pie_SliceHeights.cpp", PieSliceHeights);
USEFORM("Candle_HighLowPen.cpp", CandleHighLowPen);
USEFORM("Surface_FastBrush.cpp", SurfaceFastBrush);
USEFORM("Surface_Smoothing.cpp", SurfaceSmoothing);
USEFORM("Contour_Foot.cpp", ContourFoot);
USEFORM("ColorGrid_Realtime.cpp", ColorGridRealtime);
USEFORM("Wall_AutoHide.cpp", WallAutoHide);
USEFORM("Tool_AxisScroll.cpp", AxisScrollToolDemo);
USEFORM("Function_DownSampling.cpp", DownSampling);
USEFORM("Series_PolarBar.cpp", PolarBarForm);
USEFORM("Polar_Smooth.cpp", PolarSmoothForm);
USEFORM("Series_Groups.cpp", SeriesGroupsForm);
USEFORM("Editor_Formatting.cpp", FormatEditorDemo);
USEFORM("ChartEditor_3DGallery.cpp", Gallery3DForm);
USEFORM("DesignTime_Options.cpp", DesignTimeOptions);
USEFORMNS("..\..\..\Sources9\TeeDesignOptions.pas", Teedesignoptions, OptionsForm);
USEFORMNS("..\..\..\Sources9\TeeExpForm.pas", Teeexpform, TeeDlgWizard);
//---------------------------------------------------------------------------
WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int)
{
        try
        {
                 Application->Initialize();
                 Application->Title = "TeeChart Pro 9";
                 RegisterClass(__classid(TAreaOriginForm));
                 RegisterClass(__classid(TWelcomeForm));
                 RegisterClass(__classid(TWelcomeAllForm));
                 RegisterClass(__classid(TOrthoAngle));
                 RegisterClass(__classid(TGradientMiddle));
                 RegisterClass(__classid(TRotationCenter));
                 RegisterClass(__classid(TCanvasDotPen));
                 RegisterClass(__classid(TBrushStyleForm));
                 RegisterClass(__classid(TConesForm));
                 RegisterClass(__classid(TTruncPyramidForm));
                 RegisterClass(__classid(TTransparencyForm));
                 RegisterClass(__classid(TRightWallForm));
                 RegisterClass(__classid(TBackWallGradient));
                 RegisterClass(__classid(TBackWallImage));
                 RegisterClass(__classid(TSubTitles));
                 RegisterClass(__classid(TTitleCustomPos));
                 RegisterClass(__classid(TTitleClickEvent));
                 RegisterClass(__classid(TTitleGenFormat));
                 RegisterClass(__classid(TAxisBehind));
                 RegisterClass(__classid(TAxisCustom));
                 RegisterClass(__classid(TAxisTitleVisible));
                 RegisterClass(__classid(TAxisMillisec));
                 RegisterClass(__classid(TAxisLabelExp));
                 RegisterClass(__classid(TAxisLabelAlignForm));
                 RegisterClass(__classid(TAxisMinorGrid));
                 RegisterClass(__classid(TLegendCustomPos));
                 RegisterClass(__classid(TLegendWidths));
                 RegisterClass(__classid(TLegendCheckbox));
                 RegisterClass(__classid(TLegendImage));
                 RegisterClass(__classid(TLegendVertSpa));
                 RegisterClass(__classid(TLegendSymbolForm));
                 RegisterClass(__classid(TAxisOpaqueZone));
                 RegisterClass(__classid(TMultiAxisScroll));
                 RegisterClass(__classid(TAxisMultiRuntime));
                 RegisterClass(__classid(TGrayScaleForm));
                 RegisterClass(__classid(TChartBeforeDraw));
                 RegisterClass(__classid(TLegendStyleForm));
                 RegisterClass(__classid(TLegendCurrentPage));
                 RegisterClass(__classid(TLegendFontColor));
                 RegisterClass(__classid(TLegendGenFormat));
                 RegisterClass(__classid(TLegendSeriesForm));
                 RegisterClass(__classid(TMultiLegendForm));
                 RegisterClass(__classid(TLegendAddText));
                 RegisterClass(__classid(TPrintPreviewForm));
                 RegisterClass(__classid(TPrintPagesForm));
                 RegisterClass(__classid(TPrintPreviewNavigate));
                 RegisterClass(__classid(TPrintPreviewMulti));
                 RegisterClass(__classid(TZoomPen));
                 RegisterClass(__classid(TZoomMinPixel));
                 RegisterClass(__classid(TZoomDirection));
                 RegisterClass(__classid(TDBChartSpeed));
                 RegisterClass(__classid(TDBChartSummary));
                 RegisterClass(__classid(TDBChartOrder));
                 RegisterClass(__classid(TDBChartRecordLocate));
                 RegisterClass(__classid(TMovAveWeightedForm));
                 RegisterClass(__classid(TRSICalcForm));
                 RegisterClass(__classid(TAverageFunctionNulls));
                 RegisterClass(__classid(TMarksShadow));
                 RegisterClass(__classid(TMarksAngle));
                 RegisterClass(__classid(TMarksEvery));
                 RegisterClass(__classid(TMarksXYStyle));
                 RegisterClass(__classid(TMarksMulti));
                 RegisterClass(__classid(TMarksPositions));
                 RegisterClass(__classid(TMarksGenFormat));
                 RegisterClass(__classid(TAreaSeriesForm));
                 RegisterClass(__classid(TBezierSeriesForm));
                 RegisterClass(__classid(TBarSideAll));
                 RegisterClass(__classid(TBarStackGroup));
                 RegisterClass(__classid(TBarStackNegative));
                 RegisterClass(__classid(TBarImage));
                 RegisterClass(__classid(TBarGradient));
                 RegisterClass(__classid(TCandleCustomColors));
                 RegisterClass(__classid(TCandleOpenClose));
                 RegisterClass(__classid(TCandleAxisLabels));
                 RegisterClass(__classid(TContourSeriesForm));
                 RegisterClass(__classid(TContourLevelsForm));
                 RegisterClass(__classid(TContourView2D));
                 RegisterClass(__classid(TContourPaletteForm));
                 RegisterClass(__classid(TErrorBarNegativeForm));
                 RegisterClass(__classid(TLineStack));
                 RegisterClass(__classid(TLineClickableForm));
                 RegisterClass(__classid(TLinePatternForm));
                 RegisterClass(__classid(TLineColorEachLine));
                 RegisterClass(__classid(TPieMultiple));
                 RegisterClass(__classid(TPieShadowForm));
                 RegisterClass(__classid(TPieSemi));
                 RegisterClass(__classid(TPointerDrawCanvas));
                 RegisterClass(__classid(TPoint3DSeriesForm));
                 RegisterClass(__classid(TPoint3DEvent));
                 RegisterClass(__classid(TPolarClockWise));
                 RegisterClass(__classid(TPolarLabelsInside));
                 RegisterClass(__classid(TShapeImage));
                 RegisterClass(__classid(TShapeVertAlign));
                 RegisterClass(__classid(TSurfaceSeriesForm));
                 RegisterClass(__classid(TSurfaceSidesDemo));
                 RegisterClass(__classid(TSurfaceSmooth));
                 RegisterClass(__classid(TSurfaceFloat));
                 RegisterClass(__classid(TSurfaceFloatOther));
                 RegisterClass(__classid(TSurfaceWire));
                 RegisterClass(__classid(TSurfacePaletteForm));
                 RegisterClass(__classid(TWindAngleInc));
                 RegisterClass(__classid(TSeries3DRangePalette));
                 RegisterClass(__classid(TFreeAllSeriesForm));
                 RegisterClass(__classid(TSeriesDepth));
                 RegisterClass(__classid(TClockEdi));
                 RegisterClass(__classid(TChartGallery));
                 RegisterClass(__classid(TChartSubGallery));
                 RegisterClass(__classid(TCustomShape));
                 RegisterClass(__classid(TCursorToolDemo));
                 RegisterClass(__classid(TDragMarksToolDemo));
                 RegisterClass(__classid(TAxisArrowToolDemo));
                 RegisterClass(__classid(TDrawLineToolDemo));
                 RegisterClass(__classid(TNearestToolDemo));
                 RegisterClass(__classid(TMarkTipsToolDemo));
                 RegisterClass(__classid(TColorBandToolForm));
                 RegisterClass(__classid(TColorBandTransp));
                 RegisterClass(__classid(TColorLineForm));
                 RegisterClass(__classid(TRotateToolForm));
                 RegisterClass(__classid(TImageToolForm));
                 RegisterClass(__classid(TAxisLabelToolDemo));
                 RegisterClass(__classid(TPageNumToolDemo));
                 RegisterClass(__classid(TDragPointToolDemo));
                 RegisterClass(__classid(TChartGridForm));
                 RegisterClass(__classid(TChartEditorPanelForm));
                 RegisterClass(__classid(TGalleryPanelForm));
                 RegisterClass(__classid(TPageNavigatorForm));
                 RegisterClass(__classid(TChartWebSourceForm));
                 RegisterClass(__classid(TSeriesTextSourceForm));
                 RegisterClass(__classid(TExponentialTrendForm));
                 RegisterClass(__classid(TMomentumDivForm));
                 RegisterClass(__classid(TMACDForm));
                 RegisterClass(__classid(TStochasticForm));
                 RegisterClass(__classid(TExpMovAveForm));
                 RegisterClass(__classid(TRootMeanSqForm));
                 RegisterClass(__classid(TBollingerForm));
                 RegisterClass(__classid(TADXFunctionForm));
                 RegisterClass(__classid(TDonutSeriesForm));
                 RegisterClass(__classid(TTriSurfaceForm));
                 RegisterClass(__classid(TBoxPlotForm));
                 RegisterClass(__classid(THistogramForm));
                 RegisterClass(__classid(TColorGrid));
                 RegisterClass(__classid(TColorGridTransparent));
                 RegisterClass(__classid(THorizLineForm));
                 RegisterClass(__classid(TBarJoinForm));
                 RegisterClass(__classid(THighLowForm));
                 RegisterClass(__classid(TWaterFallForm));
                 RegisterClass(__classid(TSmithForm));
                 RegisterClass(__classid(TPyramidForm));
                 RegisterClass(__classid(TMapSeriesForm));
                 RegisterClass(__classid(TCalendarSeriesForm));
                 RegisterClass(__classid(TFunnelSeriesForm));
                 RegisterClass(__classid(TChartTransparent));
                 RegisterClass(__classid(TEditorColor));
                 RegisterClass(__classid(TSeriesDesigner));
                 RegisterClass(__classid(TChartActionsForm));
                 RegisterClass(__classid(TExportChartsForm));
                 RegisterClass(__classid(TExportTextForm));
                 RegisterClass(__classid(TExportHTMLForm));
                 RegisterClass(__classid(TExportXMLForm));
                 RegisterClass(__classid(TExportExcelForm));
                 RegisterClass(__classid(TGIFExportForm));
                 RegisterClass(__classid(TJPEGExportForm));
                 RegisterClass(__classid(TPNGExportForm));
                 RegisterClass(__classid(TPCXExportForm));
                 RegisterClass(__classid(TExportEmailForm));
                 RegisterClass(__classid(TTemplateChart));
                 RegisterClass(__classid(TChartEditorForm));
                 RegisterClass(__classid(TTeeCommanderForm));
                 RegisterClass(__classid(TChartListBoxForm));
                 RegisterClass(__classid(TOpenGLEditorForm));
                 RegisterClass(__classid(TOpenGLTriSurface));
                 RegisterClass(__classid(TOpenGLCanvas));
                 RegisterClass(__classid(TOpenGLFootBall));
                 RegisterClass(__classid(TOpenGLSurface));
                 RegisterClass(__classid(TMouseWheelForm));
                 RegisterClass(__classid(TAssignPicture));
                 RegisterClass(__classid(TDynArrays));
                 RegisterClass(__classid(TValueListModified));
                 RegisterClass(__classid(TFindMinMaxValues));
                 RegisterClass(__classid(TAreaStairsForm));
                 RegisterClass(__classid(TBarCylinderForm));
                 RegisterClass(__classid(TPrintingBugsForm));
                 RegisterClass(__classid(TColorRangeBug));
                 RegisterClass(__classid(TRemovedProperties));
                 RegisterClass(__classid(TChangesPackage));
                 RegisterClass(__classid(TChangesMisc));
                 RegisterClass(__classid(TOrderInfo));
                 RegisterClass(__classid(TBasicFeatures));
                 RegisterClass(__classid(TLineSeriesForm));
                 RegisterClass(__classid(TBarSeriesForm));
                 RegisterClass(__classid(TPieSeriesForm));
                 RegisterClass(__classid(TFastLineForm));
                 RegisterClass(__classid(THorizBarSeriesForm));
                 RegisterClass(__classid(TPointSeriesForm));
                 RegisterClass(__classid(TBubbleSeriesForm));
                 RegisterClass(__classid(TArrowSeriesForm));
                 RegisterClass(__classid(TGanttSeriesForm));
                 RegisterClass(__classid(TShapeSeriesForm));
                 RegisterClass(__classid(TCandleForm));
                 RegisterClass(__classid(TVolumeForm));
                 RegisterClass(__classid(TSurfaceHolesForm));
                 RegisterClass(__classid(TPolarForm));
                 RegisterClass(__classid(TRadarForm));
                 RegisterClass(__classid(TErrorSeriesForm));
                 RegisterClass(__classid(TWindRoseForm));
                 RegisterClass(__classid(TClockSeriesForm));
                 RegisterClass(__classid(TBar3DForm));
                 RegisterClass(__classid(TMyPointSeriesForm));
                 RegisterClass(__classid(TImageBarForm));
                 RegisterClass(__classid(TImagePointForm));
                 RegisterClass(__classid(TDeltaPointForm));
                 RegisterClass(__classid(TBigCandleForm));
                 RegisterClass(__classid(TDBChartAny));
                 RegisterClass(__classid(TDBChartSingleRecord));
                 RegisterClass(__classid(TLinkedTablesForm));
                 RegisterClass(__classid(TDBChartCrossTab));
                 RegisterClass(__classid(TPrintPreviewDialog));
                 RegisterClass(__classid(TFourChartsForm));
                 RegisterClass(__classid(TMetafileForm));
                 RegisterClass(__classid(TFunctionAddForm));
                 RegisterClass(__classid(TSubtractForm));
                 RegisterClass(__classid(THighForm));
                 RegisterClass(__classid(TLowForm));
                 RegisterClass(__classid(TCountForm));
                 RegisterClass(__classid(TMultiplyForm));
                 RegisterClass(__classid(TDivideForm));
                 RegisterClass(__classid(TAverageForm));
                 RegisterClass(__classid(TExpAveForm));
                 RegisterClass(__classid(TStdDeviationForm));
                 RegisterClass(__classid(TCurveFittingForm));
                 RegisterClass(__classid(TCurveFittingCoef));
                 RegisterClass(__classid(TDynamicTrend));
                 RegisterClass(__classid(TTrendForm));
                 RegisterClass(__classid(TCumulativeForm));
                 RegisterClass(__classid(TMovAveFunctionForm));
                 RegisterClass(__classid(TRSIFunctionForm));
                 RegisterClass(__classid(TMomentumForm));
                 RegisterClass(__classid(TFormQuality));
                 RegisterClass(__classid(TChartEditorRuntime));
                 RegisterClass(__classid(TListBoxForm));
                 RegisterClass(__classid(TDraw3DCanvas));
                 RegisterClass(__classid(TChartPrintPreviewForm));
                 RegisterClass(__classid(TChartScrollBarForm));
                 RegisterClass(__classid(TSeriesDataSetForm));
                 RegisterClass(__classid(TTeeCommanderDemo));
                 RegisterClass(__classid(TInternetCharts));
                 RegisterClass(__classid(TChartAxesForm));
                 RegisterClass(__classid(TZoomScrollForm));
                 RegisterClass(__classid(TDragBarForm));
                 RegisterClass(__classid(TLegendScroll));
                 RegisterClass(__classid(TChartClipboard));
                 RegisterClass(__classid(TChartMultiClipboard));
                 RegisterClass(__classid(TChartReports));
                 RegisterClass(__classid(TChartOther));
                 RegisterClass(__classid(TTeeCustomers));
                 RegisterClass(__classid(TAreaTransparency));
                 RegisterClass(__classid(TLineOutline));
                 RegisterClass(__classid(TPolarRadarTransp));
                 RegisterClass(__classid(TAnnotationToolForm));
                 RegisterClass(__classid(TCursorToolProg));
                 RegisterClass(__classid(TCursorSynchro));
                 RegisterClass(__classid(TDrawLineOnDragged));
                 RegisterClass(__classid(TColorLineDragRepaint));
                 RegisterClass(__classid(TChartGridColors));
                 RegisterClass(__classid(TTriSurfaceHidding));
                 RegisterClass(__classid(THistogramTransp));
                 RegisterClass(__classid(TColorGridClicked));
                 RegisterClass(__classid(TCalendarButtons));
                 RegisterClass(__classid(TExportVMLForm));
                 RegisterClass(__classid(TCommanderCustom));
                 RegisterClass(__classid(TChartMultiLanguage));
                 RegisterClass(__classid(TCandleOnGetPointer));
                 RegisterClass(__classid(TVolumeOrigin));
                 RegisterClass(__classid(TFastLineDrawAll));
                 RegisterClass(__classid(TChartEditorPageNum));
                 RegisterClass(__classid(TMarksTipMouseDelay));
                 RegisterClass(__classid(TRelease502Misc));
                 RegisterClass(__classid(TRelease502Fixed));
                 RegisterClass(__classid(TChartWizardDemo));
                 RegisterClass(__classid(TRelease501Misc));
                 RegisterClass(__classid(TRelease501Fixed));
                 // 5.03
                 RegisterClass(__classid(TAreaGradient));
                 RegisterClass(__classid(TFontGradient));
                 RegisterClass(__classid(TComboFlatForm));
                 RegisterClass(__classid(TInspectorForm));
                 RegisterClass(__classid(TChartImageForm));
                 RegisterClass(__classid(TDrawLineStyleForm));
                 RegisterClass(__classid(TRelease503Misc));
                 RegisterClass(__classid(TFastDeleteRealtime));
                 RegisterClass(__classid(TAnnotationClickForm));
                 RegisterClass(__classid(TBarSizeSeriesForm));
                 RegisterClass(__classid(TPostScriptForm));
                 RegisterClass(__classid(TGanttMouseForm));
                 RegisterClass(__classid(TRelease503Fixed));
                 // v6.0
                 RegisterClass(__classid(TAxesZPosition));
                 RegisterClass(__classid(TAxesOffsets));
                 RegisterClass(__classid(TAxisItemsDemo));
                 RegisterClass(__classid(TAxesLabelsFormat));
                 RegisterClass(__classid(TAxisLabelsFormat));
                 RegisterClass(__classid(TCanvas180Rotation));
                 RegisterClass(__classid(TGradientRadial));
                 RegisterClass(__classid(TCanvasAntiAlias));
                 RegisterClass(__classid(TCanvasRotatedEllipse));
                 RegisterClass(__classid(TRichTextDrawing));
                 RegisterClass(__classid(TLegendSymbolBorder));
                 RegisterClass(__classid(TWallTransparency));
                 RegisterClass(__classid(TChartMarginUnits));
                 RegisterClass(__classid(TChartShadow));
                 RegisterClass(__classid(TChartRoundPanel));
                 RegisterClass(__classid(TDBSummaryOrder));
                 RegisterClass(__classid(TColorLine3D));
                 RegisterClass(__classid(TAnnotationCO));
                 RegisterClass(__classid(TRotateOutline));
                 RegisterClass(__classid(TSeriesMouseEnter));
                 RegisterClass(__classid(TSeriesSortLabel));
                 RegisterClass(__classid(TMarksCallouts));
                 RegisterClass(__classid(TMarksPerPoint));
                 RegisterClass(__classid(TBarSelfStack));
                 RegisterClass(__classid(TBoxCustomForm));
                 RegisterClass(__classid(TBubbleGradient));
                 RegisterClass(__classid(TBubbleTransparency));
                 RegisterClass(__classid(TColorGridMarks));
                 RegisterClass(__classid(TColorGridBitmap));
                 RegisterClass(__classid(TContourSmooth));
                 RegisterClass(__classid(TContourOnBefore));
                 RegisterClass(__classid(TFastLineNulls));
                 RegisterClass(__classid(TPieAutoMarkPos));
                 RegisterClass(__classid(TPieOtherLegend));
                 RegisterClass(__classid(TCircledGradient));
                 RegisterClass(__classid(TPolarZones));
                 RegisterClass(__classid(TSurfaceTransp));
                 RegisterClass(__classid(TAddArray3D));
                 RegisterClass(__classid(TXYZGridding));
                 RegisterClass(__classid(TPreviewCustomDraw));
                 RegisterClass(__classid(TChartGrid3D));
                 RegisterClass(__classid(TTransposeToolDemo));
                 RegisterClass(__classid(TExtraLegendDemo));
                 RegisterClass(__classid(TSeriesAnimDemo));
                 RegisterClass(__classid(TAxesGridBands));
                 RegisterClass(__classid(TPieToolDemo));
                 RegisterClass(__classid(TXMLSourceDemo));
                 RegisterClass(__classid(TXMLSourceWeb));
                 RegisterClass(__classid(TDBCrossTabSourceDemo));
                 RegisterClass(__classid(TSmoothingFunctionDemo));
                 RegisterClass(__classid(TCustomFunctionDemo));
                 RegisterClass(__classid(TCompressionDemo));
                 RegisterClass(__classid(TCrossPointsDemo));
                 RegisterClass(__classid(TCLVFuncDemo));
                 RegisterClass(__classid(TOBVFuncDemo));
                 RegisterClass(__classid(TCCIFuncDemo));
                 RegisterClass(__classid(TPVOFuncdemo));
                 RegisterClass(__classid(TPerfFuncDemo));
                 RegisterClass(__classid(THorizAreaSeriesForm));
                 RegisterClass(__classid(TPointFigureDemo));
                 RegisterClass(__classid(TGaugeDemo));
                 RegisterClass(__classid(TVector3DSeriesForm));
                 RegisterClass(__classid(TTowerSeriesForm));
                 RegisterClass(__classid(TPDFExportForm));
                 RegisterClass(__classid(TPropertyAliases));
                 RegisterClass(__classid(TGridToChartDemo));
                 RegisterClass(__classid(TMiscVersion6));
                 RegisterClass(__classid(TRelease6Fixed));
                 RegisterClass(__classid(TGalleryAlternate));
                 // v7.0
                 RegisterClass(__classid(TChartThemes));
                 RegisterClass(__classid(TCustomPalettes));
                 RegisterClass(__classid(TAlternateAxisLabels));
                 RegisterClass(__classid(TDepthTopAxisForm));
                 RegisterClass(__classid(TLegendTitleForm));
                 RegisterClass(__classid(TBarTickLines));
                 RegisterClass(__classid(TMarkSymbols));
                 RegisterClass(__classid(TPieShadowEllipse));
                 RegisterClass(__classid(TLightToolForm));
                 RegisterClass(__classid(TSurfaceNearestForm));
                 RegisterClass(__classid(TChartListBoxRadio));
                 RegisterClass(__classid(TChartListBoxEditor));
                 RegisterClass(__classid(TCommanderCustomEditor));
                 RegisterClass(__classid(TGallerySmooth));
                 RegisterClass(__classid(TModeFunctionDemo));
                 RegisterClass(__classid(TMedianFunctionDemo));
                 RegisterClass(__classid(TCorrelationFunctionDemo));
                 RegisterClass(__classid(TVarianceDemo));
                 RegisterClass(__classid(TPerimeterDemo));
                 RegisterClass(__classid(TBubble3DSeriesForm));
                 RegisterClass(__classid(THorizHistoForm));
                 RegisterClass(__classid(TSVGExportForm));
                 RegisterClass(__classid(TPieGradientForm));
                 RegisterClass(__classid(TPoint3DBaseLine));
                 RegisterClass(__classid(TColorBandClicked));
                 RegisterClass(__classid(TCanvasSmoothStretch));
                 RegisterClass(__classid(TMiscVersion7));
                 RegisterClass(__classid(TRelease7Fixed));
                 // v7.04
                 RegisterClass(__classid(TIsometricAxis));
                 RegisterClass(__classid(TBeveledAxes));
                 RegisterClass(__classid(TDepthAxisDateTime));
                 RegisterClass(__classid(TFirstLastLabels));
                 RegisterClass(__classid(TLegendScrollBarDemo));
                 RegisterClass(__classid(TLegendSymbolDraw));
                 RegisterClass(__classid(TBar3DDepth));
                 RegisterClass(__classid(TPieSliceHeights));
                 RegisterClass(__classid(TCandleHighLowPen));
                 RegisterClass(__classid(TSurfaceFastBrush));
                 RegisterClass(__classid(TSurfaceSmoothing));
                 RegisterClass(__classid(TContourFoot));
                 RegisterClass(__classid(TColorGridRealtime));
                 RegisterClass(__classid(TWallAutoHide));
                 RegisterClass(__classid(TAxisScrollToolDemo));
                 RegisterClass(__classid(TDownSampling));
                 RegisterClass(__classid(TPolarBarForm));
                 RegisterClass(__classid(TPolarSmoothForm));
                 RegisterClass(__classid(TSeriesGroupsForm));
                 RegisterClass(__classid(TFormatEditorDemo));
                 RegisterClass(__classid(TGallery3DForm));
                 RegisterClass(__classid(TDesignTimeOptions));


                 Application->CreateForm(__classid(TTee9Form), &Tee9Form);
		Application->Run();
        }
        catch (Exception &exception)
        {
                 Application->ShowException(&exception);
        }
        return 0;
}
//---------------------------------------------------------------------------
